name: Build Theos Tweak

on: [push, workflow_dispatch]

jobs:
  build:
    runs-on: macos-14
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Theos Environment
        run: |
          bash -c "$(curl -fsSL https://githubusercontent.com)"
          echo "THEOS=$HOME/theos" >> $GITHUB_ENV
          
      - name: Download iOS SDK (Fast Clone)
        run: |
          git clone --depth=1 https://github.com $HOME/theos/sdks
          
      - name: Build Tweak Package
        run: |
          export THEOS=$HOME/theos
          make package DEBUG=0 FINALPACKAGE=1

      - name: Upload Compiled DEB & Dylib
        uses: actions/upload-artifact@v4
        with:
          name: Aimbot-Build
          path: |
            .theos/obj/debug/*.dylib
            .theos/obj/*.dylib
            packages/*.deb
          if-no-files-found: warn
